name: Pipeline Alimentos

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_alimentos
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Clonar código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar cliente MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Atualizar pip
      run: python -m pip install --upgrade pip

    - name: Instalar dependências
      run: python -m pip install -r requirements.txt

    - name: Esperar MySQL iniciar
      run: |
        for i in {1..30}; do
          mysqladmin ping -h 127.0.0.1 -u root -proot && break
          sleep 1
        done

    - name: Criar banco e tabela
      run: |
        mysql -h 127.0.0.1 -u root -proot < script.sql

    - name: Rodar testes
      run: pytest
